version: '3'
services:
  your-go-app:
    image: golang:latest
    container_name: your-go-app-container
    working_dir: /go/src/app
    volumes:
      - ../:/go/src/app
    command: go run main.go
    ports:
      - "8082:8082"