postgres:
  host: localhost
  user: postgres
  password: yours
  port: 5432
  dbname: postgres


# postgres:
#   host: localhost
#   user: rehab_ac
#   password: 2WyPnhkyy+LjU9U
#   port: 5432
#   dbname: rehab