# postgres:
#   host: localhost
#   user: rehab_ac
#   password: 2WyPnhkyy+LjU9U
#   port: 5432
#   dbname: rehab

postgres:
  host: localhost
  user: rehab
  password: password
  port: 5432
  dbname: rehab


# postgres:
#   host: localhost
#   user: rehab_ac
#   password: 2WyPnhkyy+LjU9U
#   port: 5432
#   dbname: rehab