postgres:
  host: localhost
  user: postgres
  password: yours
  port: 5432
  dbname: postgres

# postgres:
#   host: localhost
#   user: postgres
#   password: password
#   port: 5432
#   dbname: rehab